#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-h2
Version  : 4.1.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/2a/32/fec683ddd10629ea4ea46d206752a95a2d8a48c22521edd70b142488efe1/h2-4.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2a/32/fec683ddd10629ea4ea46d206752a95a2d8a48c22521edd70b142488efe1/h2-4.1.0.tar.gz
Summary  : HTTP/2 State-Machine based protocol implementation
Group    : Development/Tools
License  : MIT
Requires: pypi-h2-license = %{version}-%{release}
Requires: pypi-h2-python = %{version}-%{release}
Requires: pypi-h2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hpack)
BuildRequires : pypi(hyperframe)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
=========================
h2: HTTP/2 Protocol Stack
=========================
.. image:: https://github.com/python-hyper/h2/workflows/CI/badge.svg
:target: https://github.com/python-hyper/h2/actions
:alt: Build Status
.. image:: https://codecov.io/gh/python-hyper/h2/branch/master/graph/badge.svg
:target: https://codecov.io/gh/python-hyper/h2
:alt: Code Coverage
.. image:: https://readthedocs.org/projects/h2/badge/?version=latest
:target: https://h2.readthedocs.io/en/latest/
:alt: Documentation Status
.. image:: https://img.shields.io/badge/chat-join_now-brightgreen.svg
:target: https://gitter.im/python-hyper/community
:alt: Chat community

%package license
Summary: license components for the pypi-h2 package.
Group: Default

%description license
license components for the pypi-h2 package.


%package python
Summary: python components for the pypi-h2 package.
Group: Default
Requires: pypi-h2-python3 = %{version}-%{release}

%description python
python components for the pypi-h2 package.


%package python3
Summary: python3 components for the pypi-h2 package.
Group: Default
Requires: python3-core
Provides: pypi(h2)
Requires: pypi(hpack)
Requires: pypi(hyperframe)

%description python3
python3 components for the pypi-h2 package.


%prep
%setup -q -n h2-4.1.0
cd %{_builddir}/h2-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649695441
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-h2
cp %{_builddir}/h2-4.1.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-h2/80129bce9030cf215fc93006dce98b0ba8c778f8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-h2/80129bce9030cf215fc93006dce98b0ba8c778f8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
